### ISSUE TITLE
Carregamento do aplicativo

### ISSUE THREAD

**Issue by emiliobruno** [LEOXINGU/lftools#1]
Olá Leandro,
Parabéns pela iniciativa ! ! ! 

Quando tento ativar o plugin recebo a seguinte mensagem : 

impossível carregar complemento 'lftools' Devido a um erro ao chamar o método Class Factory(). 

ModuleNotFoundError: No module named 'xlwt' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python/plugins/lftools/__init__.py", line 38, in classFactory
    from .lftools import LFToolsPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python/plugins/lftools/lftools.py", line 41, in 
    from .lftools_provider import LFToolsProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python/plugins/lftools/lftools_provider.py", line 40, in 
    from lftools.processing_provider.Survey_Estimate3dCoord import Estimate3dCoord
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python/plugins/lftools/processing_provider/Survey_Estimate3dCoord.py", line 23, in 
    import xlwt
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'xlwt'

Versão do Python: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0] 
Versão do QGIS: 3.18.1-Zürich Zürich, 202f1bf7e5 

Caminho do Python:
/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python/plugins/geometric_attributes
/usr/share/qgis/python
/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python
/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/emilio/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/emilio/.local/share/QGIS/QGIS3/profiles/emilio/python

Um abraço, 
Emilio Bruno 
Caetité-BA

**Comment by emiliobruno** [comment]
Leandro, 

Depois das alterações, está tudo funcionando bem. 

Muito obrigado.
 EB
