### ISSUE TITLE
Impossível carregar complemento 'lftools' Devido a um erro ao chamar o método Class Factory(). 

### ISSUE THREAD

**Issue by geodourados** [LEOXINGU/lftools#4]
ModuleNotFoundError: No module named 'PIL' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\__init__.py", line 38, in classFactory
    from .lftools import LFToolsPlugin
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\lftools.py", line 41, in 
    from .lftools_provider import LFToolsProvider
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\lftools_provider.py", line 36, in 
    from lftools.processing_provider.Cart_inom2utm import Inom2utmGrid
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\processing_provider\Cart_inom2utm.py", line 21, in 
    from lftools.geocapt.imgs import Imgs
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools\geocapt\imgs.py", line 17, in 
    import math, os, base64, PIL.Image
  File "C:\Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PIL'

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.22.5-Białowieża Białowieża, c27231782f 

Caminho do Python:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:/Users/Enio/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Enio\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DsgTools

**Comment by geodourados** [comment]
Versão do QGIS
3.22.5-Białowieża
Código da versão do QGIS
c27231782f
Qt version
5.15.2
Versão do Python
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
Versão PDAL
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
Versão QScintilla2
2.11.5
OS version
Windows 10 Version 2009




Active Python plugins
AttributesJoinByLine
0.4
AutomaticBackup-master
1.0
autoSaver
2.6
AzimuthDistanceCalculator
2.0.2
AzimuthMeasurement
0.2.2
azimuth_distance_measurement
0.4
BackupLayer
0.3
dados_censo
0.40
DataPlotly
3.8.1
db-style-manager
0.8
DsgTools
4.3.0
ee_plugin
0.0.4
go2streetview
8.3
GroupStats
2.2.5
HCMGIS
21.8.28
Hqgis
1.1.1
ibama_expressions
0.4
ibge_cartography_index_map
0.4.1
landview_qgis
0.4
latlontools
3.6.3
LayerStyleLoader
0.2
mapbiomas-api
0.3.1
mapbiomasalert
1.2
mapbiomascollection
1.4
mapswipetool_plugin
1.2
NNJoin
3.1.3
numerator
0.4
openads
0.10.0
osminfo
0.7.1
qad
3.0.4
qgiscloud
3.3.12
qgsAzimuth
0.9.15
QuickMultiAttributeEdit3
version 3.0.3
quick_map_services
0.19.29
realcentroid
1.0.3
searchlayers
3.0.7
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99

**Comment by LEOXINGU** [comment]
Olá!

Esse problema está acontecendo porque seu QGIS no Mac está sendo instalado faltando o pacote PIL (do Pillow), mas dá para resolver.
Instale o Pillow pelo OSGeo Shell utilizando o comando:
`python3 -m pip install Pillow==8.4.0`
Obs.: Você deve rodar como administrador.
Se tiver qualquer dúvida na execução pode perguntar.

**Comment by geodourados** [comment]
Leandro, obrigado! Não me atentei a isso. Instalado. "Problema" corrigido.
